### ISSUE TITLE
地圖無法正常顯示

### ISSUE THREAD

**Issue by oliver-wwm** [HuskyHsu/arceus#7]
我用 chrome 和 Firefox 皆無法正常顯示地圖，會呈現一片白。
例：[黑曜原野](https://huskyhsu.github.io/arceus/#%2Fmap%3Farea=%E9%BB%91%E6%9B%9C%E5%8E%9F%E9%87%8E&keyword=pokemon-016?area=%E9%BB%91%E6%9B%9C%E5%8E%9F%E9%87%8E&keyword=pokemon-016-41)
 
但改用 Edge 卻又正常，三者皆無使用插件，請問有解嗎？

**Comment by HuskyHsu** [comment]
不好意思現在才看到
不過看了下link的url有點問題

https://huskyhsu.github.io/arceus/# `%2F` map ` %3Farea=%E9%BB%91%E6%9B%9C%E5%8E%9F%E9%87%8E&keyword=pokemon-016` ?area=%E9%BB%91%E6%9B%9C%E5%8E%9F%E9%87%8E&keyword=pokemon-016-41

正常來說是
https://huskyhsu.github.io/arceus/#/map?area=%E9%BB%91%E6%9B%9C%E5%8E%9F%E9%87%8E&keyword=pokemon-016-41
這樣才對 (`%E9%BB%91%E6%9B%9C%E5%8E%9F%E9%87%8E` 為`黑曜原野` 中文在url encode的結果)

你試試看這個能不能連到
然後上面的是在什麼操作之下變成的網址?

**Comment by oliver-wwm** [comment]
解決了，原因是 ClearUrls 這個 extension 在無痕模式下被允許載入。
進而產生錯誤的 url 連結。
我又傻傻把 chrome 的 url 直接貼到上 firefox 查看，才會以為 firefox 也異常。
感謝大大協助釐清真相。
